<a href="https://colab.research.google.com/github/sergfer26/Seminario-Deep-Reinforcement-Learning/blob/master/clase2/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Basics

El objetivo de este notebook será familiarizar al lector con las funciones de Pytorch que son:



*   Crear tensores.
*   Operar con tensores.
*   Indexar, separar y unir tensores.
*   Calcular gradientes con tensores.
*   Usar tensores de CUDA con GPU.

## Creación de Tensores

Usaremos la biblioteca ``torch`` para crear tensores.

In [0]:
import torch
import numpy as np

def describe_tensor(x):
  print("Type: {}".format(x.type()))
  print("Shape/size: {}".format(x.shape))
  print("Values: \n {}".format(x))

x = torch.Tensor(2, 4)
describe_tensor(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 4])
Values: 
 tensor([[2.5028e-36, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 6.4069e+02]])


También podemos crear tensores cuyos valores sigan alguna distribución.

In [0]:
y = torch.rand(2, 3, 4) # Uniforme(0,1)
describe_tensor(y)
z = torch.randn(2, 3, 4) # Normal std
describe_tensor(z)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3, 4])
Values: 
 tensor([[[0.0950, 0.8365, 0.1956, 0.9311],
         [0.3231, 0.7455, 0.3467, 0.4971],
         [0.8818, 0.8474, 0.3964, 0.1161]],

        [[0.4436, 0.4460, 0.4516, 0.2657],
         [0.9675, 0.1839, 0.4705, 0.3259],
         [0.6203, 0.2159, 0.7888, 0.5046]]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3, 4])
Values: 
 tensor([[[ 0.0616, -0.5176, -0.5782, -0.1833],
         [-0.7758,  0.0661,  0.4597, -0.5336],
         [ 0.7803, -1.0326,  0.6920, -0.3225]],

        [[-0.9201, -1.2559, -0.9215, -1.0630],
         [-0.5460, -0.5802,  0.0663, -0.1143],
         [-1.3410, -0.0222,  0.5675,  0.2889]]])


Más ejemplos.

In [0]:
describe_tensor(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe_tensor(x)
x.fill_(5)
describe_tensor(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[5., 5., 5.],
        [5., 5., 5.]])


Ejemplos usando lista.

In [0]:
x = torch.Tensor([[1, 2, 3], 
                  [5, 6, 7],
                  [8, 9, 10]])
describe_tensor(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
 tensor([[ 1.,  2.,  3.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])


## Operaciones con Tensores



 ### Adición.



In [0]:
w = torch.add(z, y)
describe_tensor(w)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3, 4])
Values: 
 tensor([[[ 0.1566,  0.3189, -0.3826,  0.7478],
         [-0.4527,  0.8116,  0.8064, -0.0366],
         [ 1.6621, -0.1851,  1.0884, -0.2064]],

        [[-0.4764, -0.8099, -0.4699, -0.7973],
         [ 0.4215, -0.3963,  0.5368,  0.2116],
         [-0.7207,  0.1937,  1.3563,  0.7935]]])




### Redimencionamiento



In [0]:
x = torch.arange(6)
describe_tensor(x) 

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
 tensor([0, 1, 2, 3, 4, 5])


In [0]:
x = x.view(2,3)
describe_tensor(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[0, 1, 2],
        [3, 4, 5]])


In [0]:
describe_tensor(torch.sum(x, dim=0)) # suma por primer eje

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
 tensor([3, 5, 7])


In [0]:
describe_tensor(torch.sum(x, dim=1)) # suma por segundo eje

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
 tensor([ 3, 12])


In [0]:
z = torch.arange(8)
z = z.view(2,2,2)
describe_tensor(z) #Transponer vectores
describe_tensor(torch.transpose(z, 0, 1))

Type: torch.LongTensor
Shape/size: torch.Size([8])
Values: 
 tensor([0, 1, 2, 3, 4, 5, 6, 7])
Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 2])
Values: 
 tensor([[[0, 1],
         [4, 5]],

        [[2, 3],
         [6, 7]]])




### Indexación, separación y unión de tensores 



In [0]:
describe_tensor(x[:1, :2])

Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
 tensor([[0, 1]])


In [0]:
describe_tensor(x[0,1])

Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
 1


In [0]:
indices = torch.LongTensor([0, 2])
describe_tensor(torch.index_select(x, dim=1, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
 tensor([[0, 2],
        [3, 5]])


In [0]:
indices = torch.LongTensor([0, 0])
describe_tensor(torch.index_select(x, dim=0, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
 tensor([[0, 1, 2],
        [0, 1, 2]])


In [0]:
r = torch.arange(2).long()
c = torch.arange(2).long()
describe_tensor(x[r, c])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
 tensor([0, 4])


#### Concatenación 

In [0]:
describe_tensor(torch.cat([x, x], dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
 tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [0]:
describe_tensor(torch.cat([x, x], dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
 tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


#### Apilamiento

In [0]:
describe_tensor(torch.stack([x, x]))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
 tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


### Multiplicación de tensores

In [0]:
x = x.float()
y = torch.ones(3,2)
y[:, 1] += 1
describe_tensor(y)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
 tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [0]:
describe_tensor(torch.mm(x, y))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
 tensor([[ 3.,  6.],
        [12., 24.]])


### Tensores y graficas computacionales

Hasta ahora hemos visto que los tensores de ``Pytorch`` encapusalan  información numérica que es posible manipular a través de operaciones algebraicas, de indexación y de reescalamiento. Pero requerimos de una herramienta que nos permita saber que valores corresponden a los parámetros y posteriormente calcular su gradiente. Para lo anterior usaremos la bandera ``requieres_grad`` que si tiene como valor ``True`` en algún tensor, podremos rastrear el tensor y calcular su gradiente.

In [0]:
x = torch.ones(2,2, requires_grad=True)
describe_tensor(x)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
 tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [0]:
y =(x + 2)*(x + 5) + 3
describe_tensor(y)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
 tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [0]:
z = y.mean()
describe_tensor(z)
z.backward()
# print(x.grad is None)
x.grad

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
 21.0


tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])

El método ``backward()`` calcula el valor del gradiente para un tensor donde la variable es un tensor definido anteriormente (en nuestro caso ``x``). Podemos pensar que lo que se esta calculando es su contrubución a la función de salida.

En Pytorch acceder a los gradientes de cada nodo de la gráfica computacional al usar ``.grad``. Los optimizadores usan ``.grad`` para actualizar los valores de los parámetros. 

## Tensores CUDA

In [0]:
print(torch.cuda.is_available())

False
